/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5c126fc2803b9c6fca3d3509
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ProjectService } from '../../services/project.service';
// Import Models
import { Project } from '../../domain/am_db/project';

// START - USED SERVICES
/**
* projectService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* projectService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Project
 * @class ProjectListComponent
 */
@Component({
    selector: 'app-project-list',
    templateUrl: './project-list.component.html',
    styleUrls: ['./project-list.component.css']
})
export class ProjectListComponent implements OnInit {
    list: Project[];
    search: any = {};
    idSelected: string;
    constructor(
        private projectService: ProjectService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.projectService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Project to remove
     *
     * @param {string} id Id of the Project to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Project
     */
    deleteItem() {
        this.projectService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
