/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5c126fc2803b9c6fca3d3509
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { ContactService } from '../../services/contact.service';
// Import Models
import { Contact } from '../../domain/am_db/contact';

// START - USED SERVICES
/**
* contactService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* contactService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Contact
 * @class ContactListComponent
 */
@Component({
    selector: 'app-contact-list',
    templateUrl: './contact-list.component.html',
    styleUrls: ['./contact-list.component.css']
})
export class ContactListComponent implements OnInit {
    list: Contact[];
    search: any = {};
    idSelected: string;
    constructor(
        private contactService: ContactService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.contactService.list().subscribe(list => this.list = list);
    }

    /**
     * Select Contact to remove
     *
     * @param {string} id Id of the Contact to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Contact
     */
    deleteItem() {
        this.contactService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
