<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5c126fc2803b9c6fca3d3509
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbam_dbManager.php';
	
/*
 * SCHEMA DB contact
 * 
	{
		country: {
			type: 'String'
		},
		email: {
			type: 'String'
		},
		firstName: {
			type: 'String'
		},
		lastName: {
			type: 'String'
		},
		phone: {
			type: 'String'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/contact',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'country'	=> isset($body->country)?$body->country:'',
		'email'	=> isset($body->email)?$body->email:'',
		'firstName'	=> isset($body->firstName)?$body->firstName:'',
		'lastName'	=> isset($body->lastName)?$body->lastName:'',
		'phone'	=> isset($body->phone)?$body->phone:'',
			);

	$obj = makeQuery("INSERT INTO contact (_id, country, email, firstName, lastName, phone )  VALUES ( null, :country, :email, :firstName, :lastName, :phone   )", $params, false);

	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/contact/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM contact WHERE _id = :id LIMIT 1", $params);

});
	
//CRUD - GET ONE
	
$app->get('/contact/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM contact WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/contact',	function () use ($app){
	makeQuery("SELECT * FROM contact");
});


//CRUD - EDIT

$app->post('/contact/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'country'	    => isset($body->country)?$body->country:'',
		'email'	    => isset($body->email)?$body->email:'',
		'firstName'	    => isset($body->firstName)?$body->firstName:'',
		'lastName'	    => isset($body->lastName)?$body->lastName:'',
		'phone'	    => isset($body->phone)?$body->phone:''	);

	$obj = makeQuery("UPDATE contact SET  country = :country,  email = :email,  firstName = :firstName,  lastName = :lastName,  phone = :phone   WHERE _id = :id LIMIT 1", $params, false);

	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>