<?php /** 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5c126fc2803b9c6fca3d3509
*
* You will get 10% discount for each one of your friends
* 
*/
?>
<?php
	require_once './db/dbam_dbManager.php';
	
/*
 * SCHEMA DB project
 * 
	{
		name: {
			type: 'String'
		},
		password: {
			type: 'String'
		},
		server: {
			type: 'String'
		},
		username: {
			type: 'String'
		},
		//RELAZIONI
		
		
		//RELAZIONI ESTERNE
		
		user_projects: {
			type: Schema.ObjectId,
			ref : "user"
		},
		
	}
 * 
 */


//CRUD METHODS


//CRUD - CREATE


$app->post('/project',	function () use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'name'	=> isset($body->name)?$body->name:'',
		'password'	=> isset($body->password)?$body->password:'',
		'server'	=> isset($body->server)?$body->server:'',
		'username'	=> isset($body->username)?$body->username:'',
		
	);

	$obj = makeQuery("INSERT INTO project (_id, name, password, server, username )  VALUES ( null, :name, :password, :server, :username   )", $params, false);
    
	
	echo json_encode($body);
	
});
	
//CRUD - REMOVE

$app->delete('/project/:id',	function ($id) use ($app){
	
	$params = array (
		'id'	=> $id,
	);

	makeQuery("DELETE FROM project WHERE _id = :id LIMIT 1", $params);

});
	
//CRUD - GET ONE
	
$app->get('/project/:id',	function ($id) use ($app){
	$params = array (
		'id'	=> $id,
	);
	
	$obj = makeQuery("SELECT * FROM project WHERE _id = :id LIMIT 1", $params, false);
	
	
	
	echo json_encode($obj);
	
});
	
	
//CRUD - GET LIST

$app->get('/project',	function () use ($app){
	makeQuery("SELECT * FROM project");
});


//CRUD - EDIT

$app->post('/project/:id',	function ($id) use ($app){

	$body = json_decode($app->request()->getBody());
	
	$params = array (
		'id'	=> $id,
		'name'	    => isset($body->name)?$body->name:'',
		'password'	    => isset($body->password)?$body->password:'',
		'server'	    => isset($body->server)?$body->server:'',
		'username'	    => isset($body->username)?$body->username:''
	);

	$obj = makeQuery("UPDATE project SET  name = :name,  password = :password,  server = :server,  username = :username   WHERE _id = :id LIMIT 1", $params, false);
    
	
	echo json_encode($body);
    	
});


/*
 * CUSTOM SERVICES
 *
 *	These services will be overwritten and implemented in  Custom.js
 */

			
?>